import { StyleSheet } from 'react-native';
import { Colors } from '../../../constants/Colors';
export default StyleSheet.create({
  container: { 
    marginTop:25,
alignContent:'center',
    flex: 1, 
    padding: 20, 
  },
  header: {
     marginTop:70,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    padding: 15,
    backgroundColor: '#fff',
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  monthText: { 
    fontSize: 19, 
    fontWeight: '700',
    color: '#2d3436',
    letterSpacing: 0.5,
  },
   title: {
    marginTop:50,
    fontSize: 25,
    fontWeight: '700',
    color: '#313641FF',
    marginBottom: 8,
  },
  weekHeader: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 12,
    paddingVertical: 8,
    backgroundColor: '#fff',
    borderRadius: 12,
    marginHorizontal: 8,
  },
  weekDay: { 
    width: 44, 
    textAlign: 'center', 
    fontWeight: '600',
    color: '#636e72',
    fontSize: 14,
  },
  calendarContainer: {
    paddingBottom: 20,
  },
  weekRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 6,
  },
  dayCell: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    margin: 2,
  },
  otherMonthDay: {
    backgroundColor: 'transparent',
  },
  selectedDay: {
    backgroundColor: '#6FB8FCFF',
    shadowColor: '#6FB8FCFF',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  dayText: { 
    color: '#2d3436', 
    fontSize: 16,
    fontWeight: '500',
  },
  otherMonthText: {
    color: '#b2bec3',
  },
  selectedText: {
    color: '#fff',
  },
  saveButton: {
    marginTop:50,
    marginHorizontal: 100,
    backgroundColor: '#6FB8FCFF',
    padding: 10,
    borderRadius: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 5,
    opacity: 0.9,
  },
  saveText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
});